- templates/account/login.hbs
- templates/account/manage.hbs
- templates/account/register.hbs
This PR solves issues related to the conversion between Rust strings (UTF-8) and JavaScript strings (UTF-16) in the WebAssembly module boundaries.  
**Closes #10.**
> Fix authentication issues in Safari

- .gitignore
- README.md
- alexandrie.toml
- src/config.rs
- src/db/mod.rs
As noted in this [issue](https://github.com/Hirevo/alexandrie/issues/22), sqlite requires 1 connection open when set to "WAL" (WriteAheadLog) mode. 
`diesel-rs` defaults to a connection pool [size of 10](https://docs.diesel.rs/diesel/r2d2/struct.Builder.html#method.max_size), so this PR introduces an optional config value that can be used to set that value
**Closes #22.**
> Introduce `max_conns` for DatabaseConfig

- Cargo.lock
- Cargo.toml
- docs/src/whats-available/index-management-strategies.md
- docs/src/whats-available/mod.md
- src/config/index/git2.rs
- src/config/index/mod.rs
- src/error.rs
- src/index/git2.rs
- src/index/mod.rs
**This PR depends on #18.**
This PR introduces a new strategy for managing the crate index named **`git2`**.  
This strategy makes use of the [**`libgit2`**][libgit2] library to interact with the crate index repository.  
This allows Alexandrie to operate in environments that doesn't have a **`git`** command available from the command line.  
The strategy's configuration is similar to the 'disk' one:
```toml
[index]
type = "git2"        # required
path = "crate-index" # required
```
The 'git2' strategy is only available if Alexandrie is compiled with the 'git2' feature enabled.  
The reason for this feature-gate is to reduce compilation times in case it isn't used/needed to be available.  
[libgit2]: https://libgit2.org
> Added 'git2' index management strategy

- migrations/mysql/2019-10-12-193526_initialise/up.sql
- migrations/postgres/2019-10-12-193526_initialise/up.sql
- migrations/sqlite/2019-10-12-193526_initialise/up.sql
- src/api/publish.rs
- src/api/search.rs
- src/db/models.rs
- src/frontend/krate.rs
- src/frontend/last_updated.rs
- src/frontend/most_downloaded.rs
- src/frontend/search.rs
- src/index/models.rs
This PR removes the default values for the `created_at` and `updated_at` columns of the `crates` table in all database schemas.  
So the crate publication routine now specifies any or both of these upon insertion or modification of that table.  
As an aside, this PR also renames `CrateRegistration` (in `crate::db::models`) to just `Crate`.
**Closes #32.**
> Removed defaults for creation and modification dates in database

- migrations/mysql/2019-12-28-072041_badges/down.sql
- migrations/mysql/2019-12-28-072041_badges/up.sql
- migrations/postgres/2019-12-28-072041_badges/down.sql
- migrations/postgres/2019-12-28-072041_badges/up.sql
- migrations/sqlite/2019-12-28-072041_badges/down.sql
- migrations/sqlite/2019-12-28-072041_badges/up.sql
- src/api/publish.rs
- src/db/models.rs
- src/db/schema.rs
- src/frontend/krate.rs
- src/utils/rendering.rs
- syntect-themes/frontier-contrast.tmTheme
- templates/crate.hbs
This PR adds support for showing and keeping track of the badges that crates can specify in the `[badges]` section of their `Cargo.toml` file.  
All the badges, with all their options, mentioned in [**The Cargo Book**](https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata) are supported.
> Support for crate badges

- src/api/publish.rs
- src/config/index/cli.rs
- src/index/cli.rs
- src/index/git2.rs
- src/index/mod.rs
- src/index/models.rs
- src/index/tree.rs
> refactor indexes

- Cargo.lock
- Cargo.toml
- src/config/database.rs
- src/db/mod.rs
- src/main.rs
This PR adds the following optional configuration options to `[database]`:
```toml
[database]
user = "root"
password_file = "~/file.txt"
```
This code contains multiple calls to `.expect("...")` and `panic!("...")`, which is not great but fine for configuration code (the application is not truely started yet and we wish to stop execution early).  
But I'll be investigating to improve how errors are handled more generally, both inside and outside endpoint handlers.  
The current implementation will panic if a username or password is specified both in the connection URL and its specific option.  
**Closes #30.**
> Added separate `user` and `password_file` options in database configuration

- docker/mysql/Cargo.toml
- docker/postgresql/Cargo.toml
- docker/sqlite/Cargo.toml
- src/db/mod.rs
This PR fixes the missing `url` dependency in the `Cargo.toml` files used for Docker builds.  
It also eliminates the warning `unused import: url::Url` for MySQL and PostgreSQL setups.
**Closes #48.**
> Fixed missing dependency in Docker builds

- src/index/models.rs
This PR fixes issue #58 where Alexandrie would save crate version records with some missing fields (omitted because they were empty) and this confused Cargo when `cargo build` was attempted.  
**Fixes #58.**
> Fixed issue with missing fields in index records

- src/api/account/mod.rs
- src/api/account/token/generate.rs
- src/api/account/token/info.rs
- src/api/account/token/mod.rs
- src/main.rs
This PR introduces two new endpoints for the programmatic API.  
- **`GET /api/v1/account/tokens/<name>`**: to get information about a token from its name.
- **`PUT /api/v1/account/tokens`**: to generate new authentication tokens.
It also renames the **`/api/v1/account/token`** API namespace to **`/api/v1/account/tokens`**.
> Added more API endpoints for managing tokens

- Cargo.lock
- Cargo.toml
- src/utils/rendering.rs
This PR adds a sanitization step right after the rendering a crate's README from Markdown to HTML.  
Currently, a malicious actor can theoretically publish a crate with a README containing a `<script>` tag which would read user's cookies and send it to a server somewhere.  
This sanitization step makes sure that there is no such cross-site scripting attack possible from crate READMEs, by parsing the rendered HTML and pruning sketchy HTML tags or attributes that would allow things like code execution on the client-side.  
Basically, it makes sure the content is made of purely static HTML elements.  
This sanitization is powered by the `ammonia` crate and uses defaults settings, which seems to be sane defaults, but I think I'll have to look a bit more in detail before merging it.
> Added sanitization of rendered READMEs

- src/api/crates/mod.rs
- src/api/crates/search.rs
- src/api/crates/suggest.rs
- src/main.rs
- templates/account/manage.hbs
- templates/crate.hbs
- templates/index.hbs
- templates/last-updated.hbs
- templates/most-downloaded.hbs
- templates/partials/head.hbs
- templates/partials/navbar.hbs
- templates/search.hbs
This PR adds improvements to the frontend's search bar by providing suggestions as the user types to improve the search experience. 
The suggestions are provided by a new endpoint in the programmatic API:  
`/api/v1/crates/suggest?q={some-query}&limit={some-limit}`
The suggestions are lighter to load than full search results (just names and versions) but are capped to at most 10 results, but the programmatic API endpoint allows to change that cap.
(The GIF is slowed down, I don't know why. :/)
> Improved search bar with suggestions

- .github/workflows/docs.yaml
This PR updates the version of `mdBook` used to generate the user docs in CI from `0.3.5` to `0.3.7`.  
This PR also removes the use of a Personal Access Token (this PAT was from my account) in order to automatically deploy to Github Pages, and replaces it with the built-in `GITHUB_TOKEN` secret.
> Updated `mdBook` in CI + Stopped using Personal Access Tokens

- README.md
- docs/src/SUMMARY.md
- docs/src/getting-started.md
- docs/src/installation-script.md
This PR adds more details in documentation about what is the crate index and how to setup one.  
It adds explainers for various `<...>` placeholders in documentation for values that users have to fill in for their specific installation.  
It adds a few lines explaining what is the crate index and how to setup one (also mentions the SSH issue and its workaround).  
It also adds an example shell script, written from the one that @kuruczalbert wrote in **#69**.
**Fixes #69**
> Improve documentation around setting up the crate index

- .github/workflows/e2e.yaml
The End-to-End tests need to test each scenario using multiple databases, and previously, we wrote each scenario three times (once per database tested).  
Now, we make proper use of [**GitHub Actions' support for Job Matrices**](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) to avoid that duplication of jobs and get way terser configurations.
> Changed E2E CI workflow to make use of job matrices

- Dockerfile
- e2e/images/runner/Dockerfile
This PR upgrades the Rust toolchain version used for End-to-End tests from `1.40` to `1.44`.  
This fixes the issue with the use of the rather new `matches!(...)` macro by Tide 0.12, that we're currently upgrading Alexandrie to.
> Upgraded Rust version used for E2E tests to `1.44`

- alexandrie.toml
- alexandrie/src/config/mod.rs
- alexandrie/src/main.rs
- docker/mysql/alexandrie.toml
- docker/postgres/alexandrie.toml
- docker/sqlite/alexandrie.toml
This PR changes how the server's binding address is specified in Alexandrie's configuration.  
This change allows to specify more ways to make the server available.  
One notable example of such a use case is wanting Alexandrie to operate over a Unix Domain Socket (UDS), which was previously not possible because Alexandrie required to specify an IP and a port number, which is of no use for UDS which only needs a filesystem path to a socket file.  
Now, all these cases should be handled:
```toml
[general]
bind_address = "127.0.0.1:3000"  # only serve on the loopback interface on port 3000
bind_address = "0.0.0.0:3000"    # serve on all interfaces on port 3000
bind_address = "http+unix:///home/user/alexandrie.sock"  # serve over an Unix Domain Socket on the specified path
```
**Fixes #73.**
> Allow for more freedom for the server's binding address configuration

- alexandrie/src/utils/request_log.rs
I just list some code about how compare get easy with  get `Result` or `Option`.That avoid not use `unwrap()` method.
So look like it's  easy use with `combinator` method.
```rust
struct Message(usize);
fn get_msg(msg: &Option<Message>) -> String {
let mut rep_msg = "Ok".to_string();
if let Some(msg) = msg {
rep_msg = format!("{}", msg.0)
}
rep_msg
}
fn get_msg_1(msg: &Option<Message>) -> String {
let rep_msg = if let Some(msg) = msg {
format!("{}", msg.0)
} else {
"Ok".to_string()
};
rep_msg
}
fn get_msg_2(msg: &Option<Message>) -> String {
let rep_msg = {
if let Some(msg) = msg {
format!("{}", msg.0)
} else {
"Ok".to_string()
}
};
rep_msg
}
fn get_msg_3(msg: &Option<Message>) -> String {
msg.as_ref().map(|msg| format!("{}", msg.0)).unwrap_or("Ok".to_string())
}
#[cfg(test)]
mod tests { …
```
> Simplify code using the combinators for `Option`

- docker-compose.yaml
- docs/src/whats-available/docker.md
Hello,
The UID and SIG set to [1000](https://github.com/Hirevo/alexandrie/blob/master/Dockerfile#L74) can conflict with a user existing on the host running the containers. It could be handy to have control over their value.
Since these settings are managed by some args parameters, we could use the same mechanism as for the `DATABASE` arg and replace this [block](https://github.com/Hirevo/alexandrie/blob/master/docker-compose.yaml#L8):
```
build:
context: .
args:
- DATABASE=${DATABASE}
```
by
```
build:
context: .
args:
- DATABASE=${DATABASE}
- GROUP_ID=${GROUP_ID}
- USER_ID=${USER_ID}
```
Thanks,
Hugo
> Make it possible to choose the UID/GID of the alex user

- alexandrie/src/frontend/account/login.rs
- alexandrie/src/frontend/account/manage/mod.rs
- alexandrie/src/frontend/account/manage/passwd.rs
- alexandrie/src/frontend/account/manage/tokens/mod.rs
- alexandrie/src/frontend/account/register.rs
- alexandrie/src/frontend/index.rs
- alexandrie/src/frontend/krate.rs
- alexandrie/src/frontend/last_updated.rs
- alexandrie/src/frontend/most_downloaded.rs
- alexandrie/src/frontend/search.rs
- alexandrie/src/main.rs
- alexandrie/src/utils/response/common.rs
- alexandrie/src/utils/response/mod.rs
This PR replaces a lot of unwraps with the `?` operator in order to transform what was previously panics into request-specific errors which won't shut down the whole instance.
> Removed a bunch of potentially unexpected panics

- alexandrie/src/api/crates/owners.rs
This PR refactors some code we had to make use of slice patterns to achieve clearer code that better communicates what it's actually doing than its initial implementation.  
[**Slice patterns**](https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#subslice-patterns) is a stable feature of Rust since 1.42.  
Since Tide currently makes use of the `matches!(...)` macro (which was also added in 1.42), this change does not change our MSRV (although I am not sure what that version even is for Alexandrie, currently).
> Refactor code to use the recently-stabilized slice patterns feature

- docs/src/whats-available/crate-stores.md
- docs/src/whats-available/mod.md
This PR adds an entry in the user guide to document how to configure the newly-available S3 storage strategy, as well as how to authenticate the registry to S3.
> Added S3 storage documentation in user guide

- alexandrie/src/api/crates/download.rs
- alexandrie/src/config/frontend.rs
- alexandrie/src/main.rs
- alexandrie/src/utils/request_log.rs
- alexandrie/src/utils/response/mod.rs
This PR refactors the server initialization code by separating frontend-related routes and API-related routes into separate `tide::Server` that are then simply nested into a common one.  
This change will also allow assigning different middlewares to each of them separately.
> Re-organized code for setting up the server routes

- Dockerfile
- crates/alexandrie/src/api/crates/download.rs
- crates/alexandrie/src/api/crates/info.rs
- crates/alexandrie/src/api/crates/owners.rs
- crates/alexandrie/src/api/crates/publish.rs
- crates/alexandrie/src/api/crates/search.rs
- crates/alexandrie/src/api/crates/suggest.rs
- crates/alexandrie/src/api/crates/unyank.rs
- crates/alexandrie/src/api/crates/yank.rs
- crates/alexandrie/src/config/mod.rs
- crates/alexandrie/src/db/models.rs
- crates/alexandrie/src/db/schema.rs
- crates/alexandrie/src/frontend/krate.rs
- crates/alexandrie/src/frontend/search.rs
- crates/alexandrie/src/utils/checks.rs
- crates/alexandrie/src/utils/mod.rs
- diesel.toml
- docs/src/whats-available/docker.md
- migrations/mysql/2020-08-07-205435_canonical-names/down.sql
- migrations/mysql/2020-08-07-205435_canonical-names/up.sql
- migrations/postgres/2020-08-07-205435_canonical-names/down.sql
- migrations/postgres/2020-08-07-205435_canonical-names/up.sql
- migrations/sqlite/2020-08-07-205435_canonical-names/down.sql
- migrations/sqlite/2020-08-07-205435_canonical-names/up.sql
This PR changes how the registry looks for crates by name, to account for the fact that dashes (`-`) and underscores (`_`) are considered equivalent in crate names.  
This is a change that should have been done since the beginning, since it was previously possible to publish two different crates whose canonical names are the same.  
So, after this PR, you can get information about a crate named **`async-std`** by accessing either one of:
- **`/api/v1/crates/async-std`**
- **`/api/v1/crates/async_std`** (this one was previously denied)
This applies to every endpoint mentioning any crate by name, including the frontend-related ones.
**IMPORTANT NOTE:**  
This change requires a database schema change, implemented as a diesel migration for all 3 supported database vendors.  
Since migrations …
> Added canonicalization of crate names

- crates/alexandrie/src/api/crates/publish.rs
- crates/alexandrie/src/error.rs
This PR fixes the issue that Alexandrie would always reject crate publications for versions lower than the absolute latest one.  
The more correct behaviour is to allow crate publication if the version is higher than the latest one **for that specific major version.**
It makes it possible for crates to publish bug fixes for both the latest major version and older ones that can still be maintained for compatibility reasons.
**Fixes #53.**
> Allow publishing backported crate versions

- Dockerfile
- e2e/images/runner/Dockerfile
This PR simply increases the Rust version that our CI uses from 1.50 to 1.68.
Rust 1.50 is quite old now (it is older than the 2021 edition) and caused dependencies to no longer compile during CI runs.
> Bumped MSRV for CI runs to 1.68

- crates/alexandrie-index/src/error.rs
- crates/alexandrie-index/src/tree.rs
- crates/alexandrie/src/api/crates/publish.rs
Instead of checking for ^{major}.0.0, we're checking for ^{version} now,
which should reflect the actually intended behavior. Aside of that, if
no matching version is found, we're accepting the publish, because
without that behavior you couldn't publish any incompatible updates
anymore.
Aside of that, the check was duplicated, it happened in both the API and
the index. This duplicate was removed, to make sure we don't have
conflicting checks here again in the future.
ref: #116, #119, #109
> fix: check for compatible versions only

- Cargo.lock
- crates/alexandrie-rendering/Cargo.toml
- crates/alexandrie/Cargo.toml
I half expect that these are used with some combination of features, but `cargo +nightly udeps --all-targets` claims that they are fully unused, and I couldn't find any usage either.
> fix: remove unused dependencies

- docker/startup.sh
Properly strip the SSH port suffix when deriving the host name.
Use the Bash regex feature to extract the SSH port from the URL.
> Add support for 'ssh://git@host:port/index.git' index URL syntax.

- docs/src/concepts/crate-storage.md
- docs/src/whats-available/crate-stores.md
Mentions the 's3' feature flag requirement for s3 in docs and adds links between the two storage pages.
> Include 's3' feature doc and link storage docs

- README.md
- docs/src/getting-started.md
This PR simply fixes the mention of the legacy `addr` and `port` configuration options in `[general]`, which have been replaced by `bind_address`.
> Fixed legacy configuration in examples

- crates/alexandrie/src/api/crates/owners.rs
- docs/src/programmatic-api/crates/owners/delete.md
- docs/src/programmatic-api/crates/owners/put.md
- docs/src/programmatic-api/crates/unyank/put.md
- docs/src/programmatic-api/crates/yank/delete.md
This PR addresses errors when running `cargo owner` commands.  
These errors were due to Alexandrie wrong response payload for those requests and `cargo` being unable to parse them.  
This meant that, while an error was observed, the operation of adding or removing an owner actually went completely fine.  
**Closes #156.**
> Fixed errors in `cargo owner` commands

- alexandrie.toml
- crates/alexandrie/src/config/frontend/mod.rs
- crates/alexandrie/src/config/mod.rs
- crates/alexandrie/src/frontend/index.rs
- crates/alexandrie/src/frontend/krate.rs
- crates/alexandrie/src/frontend/last_updated.rs
- crates/alexandrie/src/frontend/most_downloaded.rs
- crates/alexandrie/src/frontend/search.rs
- docker/mysql/alexandrie.toml
- docker/postgres/alexandrie.toml
- docker/sqlite/alexandrie.toml
Many users expressed the interest in restricting the anonymous browsing of the registry's crates, in the effort of allowing a truly private (in the privacy sense) crate registry.  
This PR adds a new boolean configuration option called `login_required`, which, if enabled, prevents unauthenticated users from browsing the registry using the frontend's pages.  
This, however, still does not make the registry completely opaque to anonymous users by itself, due to some of Cargo's APIs not supporting authentication as of yet.  
Cargo sends no token to these endpoints so we can't really require one, like:
- the crate search endpoint (`/api/v1/crates?<q>`), used by `cargo search`, which can be used to list all crates in the registry.  
- or the crate download endpoint …
> Disallow anonymous crate browsing in the frontend

- Cargo.lock
- crates/alexandrie/Cargo.toml
- crates/alexandrie/src/frontend/account/github/attach.rs
- crates/alexandrie/src/frontend/account/github/callback.rs
- crates/alexandrie/src/frontend/account/github/mod.rs
- crates/alexandrie/src/frontend/account/gitlab/attach.rs
- crates/alexandrie/src/frontend/account/gitlab/callback.rs
- crates/alexandrie/src/frontend/account/gitlab/mod.rs
- crates/alexandrie/src/frontend/account/login.rs
- crates/alexandrie/src/frontend/account/logout.rs
- crates/alexandrie/src/frontend/account/manage/mod.rs
- crates/alexandrie/src/frontend/account/manage/passwd.rs
- crates/alexandrie/src/frontend/account/manage/tokens/mod.rs
- crates/alexandrie/src/frontend/account/manage/tokens/revoke.rs
- crates/alexandrie/src/frontend/account/register.rs
- crates/alexandrie/src/main.rs
- crates/alexandrie/src/utils/auth/frontend.rs
- crates/alexandrie/src/utils/mod.rs
- crates/alexandrie/src/utils/sessions.rs
As @maxcountryman, the author of the `axum-sessions` crate, has kindly notified us in **#174**, `axum-sessions` has been hitting some problems due to its dependence on `async-sessions`, and a successor crate called `tower-sessions` has been released, which is free of this dependency and less limited in its API design.  
This PR, therefore, refactors Alexandrie to use this new `tower-sessions` crate instead of `axum-sessions`.
**Closes #174.**
> Move to `tower-sessions`

- crates/alexandrie/src/config/frontend/auth/mod.rs
- crates/alexandrie/src/frontend/account/login.rs
- crates/alexandrie/src/frontend/index.rs
- crates/alexandrie/src/frontend/krate.rs
- crates/alexandrie/src/frontend/last_updated.rs
- crates/alexandrie/src/frontend/most_downloaded.rs
- crates/alexandrie/src/frontend/search.rs
- templates/partials/navbar.hbs
Please review this MR related to #179
>  Hide login and register buttons if they are disabled #179 
